// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://thkabcbunmngmhcaxabr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRoa2FiY2J1bm1uZ21oY2F4YWJyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQzMTU4ODYsImV4cCI6MjA2OTg5MTg4Nn0.-mjNc4xJUB8oD20QZSRBkx9vXFDBZUwG4wcI_UQzGA0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
